### ISSUE TITLE
地址居中显示，这样有点偏了

### ISSUE THREAD

**Issue by gravitiny** [evolutionlandorg/pordria-interface#17]
![image](https://user-images.githubusercontent.com/45236466/163107519-b5a97aca-3d16-4bfd-912f-0385c0de2e8b.png)

**Comment by cxwwa** [comment]
The implementation is based on UI design @gravitiny 

<img width="1087" alt="Screen Shot 2022-04-13 at 13 53 50" src="https://user-images.githubusercontent.com/8764223/163109518-e21572b8-c801-4be3-9bc6-a14d83b3fbb3.png">
